env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/stylistic
  - plugin:vue/vue3-recommended
  - prettier
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
  project: true
  extraFileExtensions:
    - '.vue'
plugins:
  - vue
rules: {}
